from typing import BinaryIO, Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    backend_name: str

    def put(self, key: str, data: BinaryIO) -> None: ...
    def open(self, key: str) -> BinaryIO: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def url(self, key: str, expires_sec: int | None = None) -> str: ...
