"""initial schema

Revision ID: 5576d99dad91
Revises: 
Create Date: 2026-05-29 14:47:50.139848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5576d99dad91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polyelectrolytes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('charge_sign', sa.SmallInteger(), nullable=False),
    sa.Column('charge_group', sa.String(length=64), nullable=False),
    sa.Column('is_strong', sa.Boolean(), nullable=False),
    sa.Column('pka', sa.Float(), nullable=True),
    sa.Column('monomer_mw_g_mol', sa.Float(), nullable=False),
    sa.Column('monomer_smiles', sa.Text(), nullable=False),
    sa.Column('backbone_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('substrate', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_id', 'name', name='uq_sample_experiment_name')
    )
    op.create_table('layers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('polyelectrolyte_id', sa.String(length=32), nullable=False),
    sa.Column('molecular_weight_kda', sa.Float(), nullable=True),
    sa.Column('concentration_mg_ml', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('salt_concentration_m', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['polyelectrolyte_id'], ['polyelectrolytes.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'position', name='uq_layer_sample_position')
    )
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('parser_name', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('width_um', sa.Float(), nullable=True),
    sa.Column('height_um', sa.Float(), nullable=True),
    sa.Column('pixels_x', sa.Integer(), nullable=True),
    sa.Column('pixels_y', sa.Integer(), nullable=True),
    sa.Column('units', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=True),
    sa.Column('sample_id', sa.UUID(), nullable=True),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('extractor_scope', sa.String(length=16), nullable=False),
    sa.Column('params_hash', sa.String(length=40), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scan_id IS NOT NULL AND sample_id IS NULL AND extractor_scope = 'scan') OR (scan_id IS NULL AND sample_id IS NOT NULL AND extractor_scope = 'sample')", name='ck_feature_scan_xor_sample'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_values_gin', 'features', ['values'], unique=False, postgresql_using='gin')
    op.create_index('uq_feature_sample_extractor', 'features', ['sample_id', 'extractor_name', 'extractor_version', 'params_hash'], unique=True, postgresql_where='sample_id IS NOT NULL')
    op.create_index('uq_feature_scan_extractor', 'features', ['scan_id', 'extractor_name', 'extractor_version', 'params_hash'], unique=True, postgresql_where='scan_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_feature_scan_extractor', table_name='features', postgresql_where='scan_id IS NOT NULL')
    op.drop_index('uq_feature_sample_extractor', table_name='features', postgresql_where='sample_id IS NOT NULL')
    op.drop_index('ix_feature_values_gin', table_name='features', postgresql_using='gin')
    op.drop_table('features')
    op.drop_table('scans')
    op.drop_table('layers')
    op.drop_table('samples')
    op.drop_table('polyelectrolytes')
    op.drop_table('exports')
    op.drop_table('experiments')
    # ### end Alembic commands ###
